name: financeiro_pessoal
description: Sistema Financeiro Pessoal

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# version:A.B.C+X --> A.B.C represents the versionName such as 1.0.0 - X (the number after the +) represents the versionCode such as 1, 2, 3, etc.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  intl:
  get: 5.0.0-release-candidate-9.3.2
  http: ^1.3.0
  drift: ^2.26.0
  sqlite3_flutter_libs: ^0.5.32
  path_provider: ^2.1.5
  path: ^1.9.1
  pluto_grid: ^8.0.0
  flutter_bootstrap: any
  email_validator: ^3.0.0
  pdf:
  printing: ^5.14.2
  extended_masked_text: ^3.0.1
  recase: ^4.1.0
  buttons_tabbar: ^1.3.15
  universal_html: ^2.2.4
  permission_handler: ^11.4.0
  file_picker: ^10.0.0
  fl_chart: 0.69.0
  xml: ^6.5.0

  flex_color_scheme: ^8.2.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dependency_overrides:
  analyzer: 7.3.0

dev_dependencies:
  build_runner: ^2.4.15
  build_web_compilers: ^4.1.4
  drift_dev:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/launcher_icon.png" 

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

    # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/fonts/
     - assets/fonts/report/


# Flutter Doctor from Vycanis Machine
# Doctor summary (to see all details, run flutter doctor -v):
# [√] Flutter (Channel stable, 3.29.3, on Microsoft Windows [versÆo 10.0.19045.5487], locale pt-BR)
# [√] Windows Version (10 Pro 64-bit, 22H2, 2009)
# [√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
# [√] Chrome - develop for the web
# [√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.3)
# [√] Android Studio (version 2021.2)
# [√] VS Code (version 1.99.3)
# [√] Connected device (3 available)
# [√] Network resources